### ISSUE TITLE
NullPointerException Error, in version 1.0.1 master branch

### ISSUE THREAD

**Issue by yongks** [nishutayal/kafka-connect-hbase#13]
I'm new to this. Had been google around for few hours. I had installed confluent and hbase, both started successfully in my mahine... Now wanted to try out this connetor, but stuck at where to find 'hbase-sink.jar' ?

**Comment by nishutayal** [comment]
You should be able to find "kafka-connect-hbase-1.0.0.jar" in below directory:

`<confluent-installation-dir>/share/confluent-hub-components/nishutayal-kafka-connect-hbase/lib`

**hbase-sink.jar** and **kafka-connect-hbase-1.0.0.jar** - both are same.

**Comment by yongks** [comment]
Thanks for the quick response. I managed to get the connector running, however, when I fire my datagen producer (tried both json and avro format), I get "java.lang.NullPointerException" error. I believe this is fixed in #6 . However, the library I downloaded through confluent_hub is the initial version (1.0). Is there a way I can download the new sink jar, without recompiling from source ?

**Comment by yongks** [comment]
I just download 1.0.1 from github and recompiled it using maven package.. But still having the same NullPointerException error.

When I run this:

```
$CONFLUENT_HOME/bin/connect-standalone \
$CONFLUENT_HOME/etc/schema-registry/connect-avro-standalone.properties \
$CONFLUENT_HOME/share/java/kafka-connect-hbase-1.0.1/hbase-sink-connector.properties

```
I get this:
```
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
        at org.apache.hadoop.hbase.client.Put.<init>(Put.java:68)
        at org.apache.hadoop.hbase.client.Put.<init>(Put.java:58)
```

Here is my  property file:

```
name=kafka-cdc-hbase
connector.class=io.svectors.hbase.sink.HBaseSinkConnector
tasks.max=1
topics=destTable2
zookeeper.quorum=localhost:2181
#event.parser.class=io.svectors.hbase.parser.AvroEventParser
event.parser.class=io.svectors.hbase.parser.JsonEventParser
# properties for hbase table 'test'
hbase.table.name=destTable2
hbase.destTable2.rowkey.columns=id
hbase.destTable2.rowkey.delimiter=|
hbase.destTable2.family=d
# incase of more than one column family, define the column mapping
#hbase.test.family=c
#hbase.test.c.columns=c1,c2
```
And here is my datagen producer:
```
222.173.165.103 --> ([ '222.173.165.103' | 1 | '-' | '20/May/2019:10:33:53 -0700' | 1558373633173 | 'GET /index.html HTTP/1.1' | '407' | '2048' | '-' | 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)' ]) ts:1558373633412
222.90.225.227 --> ([ '222.90.225.227' | 27 | '-' | '20/May/2019:10:33:59 -0700' | 1558373639773 | 'GET /site/login.html HTTP/1.1' | '200' | '2048' | '-' | 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36' ]) ts:1558373639774
222.168.57.122 --> ([ '222.168.57.122' | 28 | '-' | '20/May/2019:10:34:00 -0700' | 1558373640610 | 'GET /index.html HTTP/1.1' | '200' | '1289' | '-' | 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)' ]) ts:1558373640611
^Cyongks@edgenode-2:~$ ksql-datagen quickstart=clickstream topic=destTable2 format=json iterations=1000 maxInterval=10000
```
I had spent whole day doing this with no success. Before going for json format, I had tried avro format but hit into union fields of non-supported **'converter.enhanced.avro.schema.support=true'** issue (get **magic byte, id = -1** error).

Very frustrating. Hopefully can get enlightenment here.

**Comment by nishutayal** [comment]
In the above sample data, it isn't a valid JSON structure. Can you please make sure if the the topic has proper JSON data?

**Comment by yongks** [comment]
> In the above sample data, it isn't a valid JSON structure. Can you please make sure if the the topic has proper JSON data?

The ksql-datagen was specified with parameter format=json.  Below is the confirmation that the consumer receiving it as **valid json** format. I believe the connector should receive 
```
$/usr/local/confluent/share/java/kafka-connect-hbase-1.0.1$ confluent consume destTable2
{"ip":"233.173.215.103","userid":15,"remote_user":"-","time":"20/May/2019:20:11:18 -0700","_time":1558408278253,"request":"GET /site/user_status.html HTTP/1.1","status":"407","bytes":"4096","referrer":"-","agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"}
{"ip":"222.168.57.122","userid":28,"remote_user":"-","time":"20/May/2019:20:11:23 -0700","_time":1558408283639,"request":"GET /site/login.html HTTP/1.1","status":"407","bytes":"2048","referrer":"-","agent":"Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"}
{"ip":"111.168.57.122","userid":35,"remote_user":"-","time":"20/May/2019:20:11:26 -0700","_time":1558408286177,"request":"GET /site/user_status.html HTTP/1.1","status":"405","bytes":"4096","referrer":"-","agent":"Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"}
```

Here is the command I use to run the connector:
```
$CONFLUENT_HOME/bin/connect-standalone \
$CONFLUENT_HOME/share/java/kafka-connect-hbase-1.0.1/connect-standalone-json.properties \
$CONFLUENT_HOME/share/java/kafka-connect-hbase-1.0.1/hbase-sink-connector.properties
```
Here is the **connect-standalone-json.properties** file:
```
key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=org.apache.kafka.connect.json.JsonConverter

key.converter.schemas.enable=false
value.converter.schemas.enable=false

internal.key.converter=org.apache.kafka.connect.storage.StringConverter
internal.value.converter=org.apache.kafka.connect.json.JsonConverter
internal.key.converter.schemas.enable=false
internal.value.converter.schemas.enable=false
```
Here is the **hbase-sink-connector.properties** file:

```
name=kafka-cdc-hbase
connector.class=io.svectors.hbase.sink.HBaseSinkConnector
tasks.max=1
topics=destTable2
zookeeper.quorum=localhost:2181
#event.parser.class=io.svectors.hbase.parser.AvroEventParser
event.parser.class=io.svectors.hbase.parser.JsonEventParser
hbase.table.name=destTable2
hbase.destTable2.rowkey.columns=id
hbase.destTable2.rowkey.delimiter=|
hbase.destTable2.family=d
# incase of more than one column family, define the column mapping
#hbase.test.family=c
#hbase.test.c.columns=c1,c2
#hbase.test.d.columns=d1,d2
```
Here is my hbase **destTable2** table (on the same host):

```
hbase(main):001:0> scan 'destTable2'
ROW                            COLUMN+CELL                                                                          
0 row(s) in 0.6510 seconds

hbase(main):002:0> describe 'destTable2'
Table destTable2 is ENABLED                                                                                         
destTable2                                                                                                          
COLUMN FAMILIES DESCRIPTION                                                                                         
{NAME => 'c', BLOOMFILTER => 'ROW', VERSIONS => '1', IN_MEMORY => 'false', KEEP_DELETED_CELLS => 'FALSE', DATA_BLOCK
_ENCODING => 'NONE', TTL => 'FOREVER', COMPRESSION => 'NONE', MIN_VERSIONS => '0', BLOCKCACHE => 'true', BLOCKSIZE =
> '65536', REPLICATION_SCOPE => '0'}                                                                                
1 row(s) in 0.2060 seconds
```

Here are the **errors**:
```
[2019-05-20 20:25:00,684] ERROR WorkerSinkTask{id=kafka-cdc-hbase-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:177)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:560)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:321)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
```

**Comment by yongks** [comment]
I tested with a **Filesink** with the same setup, format and converter, and it was successful. What changed is only sink.

This make me suspect that the hbase connector didn't pick up the **row key** value from stream, and hence error occured  when inserting **null** into hbase.

**I wonder which value did the connector pickup as hbase rowkey ?  **

The example given in this documentation uses **avro** with rowkey.columns defined as one of the source column label.

In my case, I had tried different column for the rowkey base on the source json string, but still no success.
```
#hbase.destTable2.rowkey.columns=id
hbase.destTable2.rowkey.columns=userid
```

**Comment by yongks** [comment]
Ah... I finally got it working with json.  My mistake is at the hbase connector config:

- hbase.destTable2.rowkey.columns=... must be a column label for the source json
- hbase.destTable2.family=... must be a valid column family

However, the rowkey values I gotten in hbase are all 4 words HEX..  **\x00\x00\x00\x13**. The source is integer. 

Wonder is there anyway to fix it within the connector or sink properties ?

**Comment by nishutayal** [comment]
Good to hear that.  
The rowkey column should be a valid attribute from the source json.   Regarding the integer to String mapping, I noticed the issue, will fix it.  Thanks for pointing out. 👍
