### ISSUE TITLE
NullPointerException when i used jsonConverter

### ISSUE THREAD

**Issue by sure0000** [nishutayal/kafka-connect-hbase#17]
## when i run hbase connect with json schema, i got those exception, i read the code but don't konw why those happen

**here is my config** 
```json
{
	"name": "sink_hbase_test01",
	"config": {
		"connector.class": "io.svectors.hbase.sink.HBaseSinkConnector",
		"tasks.max": 1,
		"topics": "xyc_test_001_dc_open_data_applicants",
		"zookeeper.quorum": "data153:12181",
		"event.parser.class": "io.svectors.hbase.parser.JsonEventParser",
		"hbase.table.name": "xyc_hbase_sink",
		"hbase.xyc_hbase_sink.rowkey.columns": "id",
		"hbase.xyc_hbase_sink.rowkey.delimiter": "|",
		"hbase.xyc_hbase_sink.family": "cf"
	}

}
```

**and when i run with this config , i got this exception**:

```
[2020-08-14 10:44:14,698] ERROR Task sink_hbase_test01-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerSinkTask:495)
io.svectors.hbase.parser.EventParsingException: Failed to parse the schema [Schema{dc_open_data_applicants:STRUCT}] , value [Struct{id=147,open_data_id=101,applicant=test116,status=applying,remarks=test,create_time=Fri Aug 14 10:44:04 CST 2020,update_time=Fri Aug 14 10:44:04 CST 2020}] with ex [null]
	at io.svectors.hbase.parser.JsonEventParser.parse(JsonEventParser.java:146)
	at io.svectors.hbase.parser.JsonEventParser.parseValue(JsonEventParser.java:78)
	at io.svectors.hbase.util.ToPutFunction.apply(ToPutFunction.java:66)
	at io.svectors.hbase.sink.HBaseSinkTask.lambda$put$0(HBaseSinkTask.java:76)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at io.svectors.hbase.sink.HBaseSinkTask.lambda$put$1(HBaseSinkTask.java:76)
	at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1321)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1691)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at io.svectors.hbase.sink.HBaseSinkTask.put(HBaseSinkTask.java:75)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:477)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:278)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:195)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:163)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:146)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:190)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.apache.hadoop.hbase.util.Bytes.toBytes(Bytes.java:677)
	at io.svectors.hbase.parser.JsonEventParser.toValue(JsonEventParser.java:164)
	at io.svectors.hbase.parser.JsonEventParser.parse(JsonEventParser.java:124)
......

[2020-08-14 10:44:14,699] ERROR Task sink_hbase_test01-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:148)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:497)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:278)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:195)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:163)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:146)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:190)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

@nishutayal could you help me for that? I have been working on that for  days .

**Comment by sure0000** [comment]
# bug
## i already sloved the problem， if your data contain null , the code of below will throw exception:

![image](https://user-images.githubusercontent.com/18415138/90215206-8f762280-de2d-11ea-8753-4699aa127a78.png)

**Comment by SpenserZC** [comment]
Could you tell me , how to sloved the problem ? my data has null.,such as {"id":1234,"name":null}.

**Comment by sure0000** [comment]
I think there are two way to solve this problem:

1. Convert  Object null in your data to String 
2. Modify the source code and recompile: when you data is null return null

**Comment by SpenserZC** [comment]
> I think there are two way to solve this problem:
> 
> 1. Convert  Object null in your data to String
> 2. Modify the source code and recompile: when you data is null return null

OK，thank sure0000. I had solved this problem.
