### ISSUE TITLE
 No rowkey has been configured for table 

### ISSUE THREAD

**Issue by VarunKashyapKuturu** [nishutayal/kafka-connect-hbase#4]
i am facing this below errors while trying to follow the implementation steps, is there anything more we have to do tp configure the row key.
i am also putting here the the sample data which is in my kafka topic, please have a look
ERROR Thread WorkerSinkTask-kafka-cdc-hbase-0 exiting with uncaught exception:  (org.apache.kafka.connect.util.ShutdownableThread:84)
org.apache.kafka.common.config.ConfigException:  No rowkey has been configured for table [hbase.ASSET_LOCATIONS_2.rowkey.columns]
        at io.svectors.hbase.config.HBaseSinkConfig.validate(HBaseSinkConfig.java:79)
        at io.svectors.hbase.sink.HBaseSinkTask.start(HBaseSinkTask.java:59)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.joinConsumerGroupAndStart(WorkerSinkTask.java:154)
        at org.apache.kafka.connect.runtime.WorkerSinkTaskThread.execute(WorkerSinkTaskThread.java:54)
        at org.apache.kafka.connect.util.ShutdownableThread.run(ShutdownableThread.java:82)
Exception in thread "WorkerSinkTask-kafka-cdc-hbase-0" org.apache.kafka.common.config.ConfigException:  No rowkey has been configured for table [hbase.ASSET_LOCATIONS_2.rowkey.columns]

**My Data in Kafka topic looks like this**
{"schema":{"type":"struct","fields":[{"type":"int32","optional":true,"field":"ID"},{"type":"string","optional":true,"field":"NAME"},{"type":"double","optional":true,"field":"LAT"}],"optional":false},"payload":{"ID":1,"NAME":"Siesta Key Beach","LAT":27.266024}}
{"schema":{"type":"struct","fields":[{"type":"int32","optional":true,"field":"ID"},{"type":"string","optional":true,"field":"NAME"},{"type":"double","optional":true,"field":"LAT"}],"optional":false},"payload":{"ID":2,"NAME":"The Dali Museum","LAT":27.765829}}
{"schema":{"type":"struct","fields":[{"type":"int32","optional":true,"field":"ID"},{"type":"string","optional":true,"field":"NAME"},{"type":"double","optional":true,"field":"LAT"}],"optional":false},"payload":{"ID":3,"NAME":"The Florida Aquarium","LAT":27.945387}}

**Comment by nishutayal** [comment]
It seems the property ` hbase.<topicname>.rowkey.columns` is missing. Can you share your properties file?

**Comment by VarunKashyapKuturu** [comment]
Sorry, I did not mention/change the hbase table name properly in the properties file which is causing the exception. i will close this but i am still having couple errors can you please find my properties file and error log to give your insights

**Comment by VarunKashyapKuturu** [comment]
[2018-11-13 22:18:44,933] INFO Kafka version : 0.9.0.0 (org.apache.kafka.common.utils.AppInfoParser:82)
[2018-11-13 22:18:44,933] INFO Kafka commitId : fc7243c2af4b2b4a (org.apache.kafka.common.utils.AppInfoParser:83)
[2018-11-13 22:18:44,935] INFO Created connector kafka-cdc-hbase (org.apache.kafka.connect.cli.ConnectStandalone:82)
[2018-11-13 22:18:48,074] INFO HBaseSinkConfig values:
        event.parser.class = io.svectors.hbase.parser.JsonEventParser
        zookeeper.quorum = ec2-52-34-185-180.us-west-2.compute.amazonaws.com:2181
(io.svectors.hbase.config.HBaseSinkConfig:165)
[2018-11-13 22:18:48,215] INFO Sink task org.apache.kafka.connect.runtime.WorkerSinkTask@55b88238 finished initialization and start (org.apache.kafka.connect.runtime.WorkerSinkTask:155)
[2018-11-13 22:18:48,215] INFO org.apache.kafka.connect.runtime.WorkerSinkTask@55b88238 Committing offsets (org.apache.kafka.connect.runtime.WorkerSinkTask:187)
[2018-11-13 22:18:48,234] INFO org.apache.kafka.connect.runtime.WorkerSinkTask@55b88238 Committing offsets (org.apache.kafka.connect.runtime.WorkerSinkTask:187)
[2018-11-13 22:18:48,235] INFO Fetch offset null is out of range, resetting offset (org.apache.kafka.clients.consumer.internals.Fetcher:567)
[2018-11-13 22:18:48,238] INFO org.apache.kafka.connect.runtime.WorkerSinkTask@55b88238 Committing offsets (org.apache.kafka.connect.runtime.WorkerSinkTask:187)
[2018-11-13 22:18:48,351] WARN Unable to load native-hadoop library for your platform... using builtin-java classes where applicable (org.apache.hadoop.util.NativeCodeLoader:62)
[2018-11-13 22:18:48,578] INFO Process identifier=hconnection-0x4b6e5c49 connecting to ZooKeeper ensemble=ec2-52-34-185-180.us-west-2.compute.amazonaws.com:2181 (org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper:120)
[2018-11-13 22:18:48,607] INFO ClusterId read in ZooKeeper is null (org.apache.hadoop.hbase.client.ZooKeeperRegistry:107)
[2018-11-13 22:18:48,660] INFO Closing zookeeper sessionid=0x1670d9e75631119 (org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation:1709)
[2018-11-13 22:18:48,662] ERROR Task kafka-cdc-hbase-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerSinkTask:302)
[2018-11-13 22:18:48,662] ERROR Task is being killed and will not recover until manually restarted: (org.apache.kafka.connect.runtime.WorkerSinkTask:303)
io.svectors.hbase.sink.SinkConnectorException: Failed with a [java.lang.NullPointerException] when writing to table [ASSET_LOCATIONS]
        at io.svectors.hbase.HBaseClient.write(HBaseClient.java:56)
        at io.svectors.hbase.HBaseClient.write(HBaseClient.java:43)
        at io.svectors.hbase.sink.HBaseSinkTask.lambda$put$2(HBaseSinkTask.java:80)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1691)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
        at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
        at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583)
        at io.svectors.hbase.sink.HBaseSinkTask.put(HBaseSinkTask.java:79)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:280)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:176)
        at org.apache.kafka.connect.runtime.WorkerSinkTaskThread.iteration(WorkerSinkTaskThread.java:90)
        at org.apache.kafka.connect.runtime.WorkerSinkTaskThread.execute(WorkerSinkTaskThread.java:58)
        at org.apache.kafka.connect.util.ShutdownableThread.run(ShutdownableThread.java:82)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
        at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithoutRetries(RpcRetryingCaller.java:208)
        at 

**properties file:**
name=kafka-cdc-hbase
connector.class=io.svectors.hbase.sink.HBaseSinkConnector
tasks.max=1
topics=ASSET_LOCATIONS
zookeeper.quorum=myhost:2181
event.parser.class=io.svectors.hbase.parser.JsonEventParser

# properties for hbase table 'test'
hbase.ASSET_LOCATIONS.rowkey.columns=ID
hbase.ASSET_LOCATIONS.rowkey.delimiter=|
hbase.ASSET_LOCATIONS.family=asset_info

**Comment by nishutayal** [comment]
It seems to be the access issue with your hbase cluster. Have you bundled the connector jar with your hbase-site.xml?

**Comment by nishutayal** [comment]
Since there are no question back from OP, hence closing the issue.
